import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/SmoothScroll";
import CursorAnimation from "@/components/CursorAnimation";
import Navbar from "@/components/Navbar";
import InteractiveGrid from "@/components/3d/InteractiveGrid";
import TerminalButton from "@/components/TerminalButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased selection:bg-primary/30 selection:text-white`}
      >
        <SmoothScroll>
          <InteractiveGrid />
          <CursorAnimation />
          <Navbar />
          <main className="relative flex flex-col min-h-screen">
            {children}
          </main>
          <TerminalButton />
        </SmoothScroll>
      </body>
    </html>
  );
}
